#%RAML 1.0
title: Migración API proactivo-hermes
description: !include docs/apiDescription.md
version: v0.1.0 
baseUri: https://www.bbvaapis.com/risk-limits/v0

uses:
  annotations: ../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  data: types/behavioral-evaluations/data.raml

annotationTypes:
  enumDescription: !include ../glapi-global-apis-commons-commons/annotations/enumDescription.raml

resourceTypes:
  collection: !include ../glapi-global-apis-commons-commons/resourceTypes/collection.raml
  collection-item: !include ../glapi-global-apis-commons-commons/resourceTypes/collection-item.raml
  subresource-collection: !include ../glapi-global-apis-commons-commons/resourceTypes/subresource-collection.raml

types:
  errors: !include ../glapi-global-apis-commons-commons/types/errors.raml

/behavioral-evaluations: 
  description: |
    Manage information about the client's proactve hermes.

  /{customerId}: 
    description: |
      Represents a client's score with the purpose of future commercial offers. 
    type: collection-item
    uriParameters:
      customerId:
        description: "Identification number of a BBVA customer".
        type: string
        example: "02601264"

    get:
      description: |
        Obtain client data stored in the system (Hermes Score).

      responses:
        200:
          description: OK
          body:
            application/json:
              example: !include  examples/behavioral-evaluations/customer-id/get_200.json
              type: object
              properties:
                data:
                  type: data.data
        400:
          description: Bad request.
          body:
            application/json:
              type: errors
              examples:
                 invalidParameters:
                   value: !include examples/behavioral-evaluations/customer-id/get_400_invalidParameters.json
                   description: The request could not be completed due to invalid parameters.
                   displayName: Invalid parameters.
