#%RAML 1.0
title: Risk Limits
description: !include docs/apiDescription.md
version: v0.1.0
baseUri: https://www.bbvaapis.com/risk-limits/v0

uses:
  annotations: ../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  behavioralEvaluations: types/behavioral-evaluations/behavioralEvaluations.raml

annotationTypes:
  enumDescription: !include ../glapi-global-apis-commons-commons/annotations/enumDescription.raml

resourceTypes:
  collection: !include ../glapi-global-apis-commons-commons/resourceTypes/collection.raml
  collection-item: !include ../glapi-global-apis-commons-commons/resourceTypes/collection-item.raml
  subresource-collection: !include ../glapi-global-apis-commons-commons/resourceTypes/subresource-collection.raml

types:
  errors: !include ../glapi-global-apis-commons-commons/types/errors.raml

/behavioral-evaluations:
    description: |
      Manage information about the customer's behavioral evaluations.
    type: collection

    get:
      description: |
        Retrieves information about customer's behavioral evaluations. In Argentina, it is information that resides in the Hermes scoring system.
      queryParameters:
        customerid:
          description: | 
            "Unique identifier of a customer, to be used only for attended channels."
          type: string
          required: false
          example: "02601264"
      responses:
        200:
          description: Ok.
          body:
            application/json:
              example: !include examples/behavioral-evaluations/customer-id/get_200.json
              type: object
              properties:
                data:
                  type: behavioralEvaluations.behavioralEvaluations
        400:
          description: Bad request.
          body:
            application/json:
              type: errors
              examples:
                 invalidParameters:
                   value: !include examples/behavioral-evaluations/customer-id/get_400_invalidParameters.json
                   description: |
                      The request could not be completed due to invalid parameters.
                   displayName: Invalid parameters.
