#%RAML 1.0 lIBRARY

types:
  messages:
    type: array
    items: 
      properties:
        code:
          description: Message code.
          type: string
        message:
          description: Message description.
          type: string
        type: 
          description: Message type. 
          type: string
