#%RAML 1.0 Library
uses:
  annotations: ../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  lastPayrollIncome: lastPayrollIncome.raml
  riskSegment: riskSegment.raml 

types:
  behavioralEvaluations:
    type: array
    items:
      properties:
        id:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: string
          description: | 
            Represents the unique identifier of a customer.
          required: false
        exclusionReasonCode:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: string
          description: | 
            Represents the reason code of the exclusion.
          required: false
        riskGroup:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: string
          description: | 
            The risk group to which the customer belongs.
          required: false
        lastSalaryAccreditation:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: number
          description: | 
            Represents the number of months that have elapsed since the last salary payment in the customer's account.
          required: false
        totalMonthsPayroll:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: number
          description: | 
            Total number of months of the customer's payroll.
          required: false
        payrollCompanyCode:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: string
          description: |
            Represents the code of the Payroll Company. (The AST Code in Argentina).
          required: false
        numberTotalAccreditations:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: number
          description: |
            Represents the numbers of accreditations in the customer's account.
          required: false
        lastPayrollIncome:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: lastPayrollIncome.lastPayrollIncome
          description: | 
            The amount of the last payroll accreditation.
          required: false
        riskSegment:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: riskSegment.riskSegment
          description: | 
            The risk segment is a code used by BBVA to segment customers by type. We use it to identify what type of customer is.
          required: false
        riskScore:
          (annotations.bindingDefinition):
            - method: "GET"
              input: "NONE"
              output: "REQUIRED"
          type: number
          description: |
            Represents the score calculated in the model Proactivo Hermes Bureau.
          required: false
